package com.myspace.sample;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Machine implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String os;

	private java.lang.String application;

	public Machine() {
	}

	public java.lang.String getOs() {
		return this.os;
	}

	public void setOs(java.lang.String os) {
		this.os = os;
	}

	public java.lang.String getApplication() {
		return this.application;
	}

	public void setApplication(java.lang.String application) {
		this.application = application;
	}

	public Machine(java.lang.String os, java.lang.String application) {
		this.os = os;
		this.application = application;
	}

}