package com.myspace.sample;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Request implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.Integer port;
	private java.lang.String tier;
	private java.lang.String application;
	private java.lang.String zone;

	public Request() {
	}

	public java.lang.Integer getPort() {
		return this.port;
	}

	public void setPort(java.lang.Integer port) {
		this.port = port;
	}

	public java.lang.String getTier() {
		return this.tier;
	}

	public void setTier(java.lang.String tier) {
		this.tier = tier;
	}

	public java.lang.String getApplication() {
		return this.application;
	}

	public void setApplication(java.lang.String application) {
		this.application = application;
	}

	public java.lang.String getZone() {
		return this.zone;
	}

	public void setZone(java.lang.String zone) {
		this.zone = zone;
	}

	public Request(java.lang.Integer port, java.lang.String tier,
			java.lang.String application, java.lang.String zone) {
		this.port = port;
		this.tier = tier;
		this.application = application;
		this.zone = zone;
	}

}