package com.myspace.sample;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class RuleOutcome implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String outcome;

	public RuleOutcome() {
	}

	public java.lang.String getOutcome() {
		return this.outcome;
	}

	public void setOutcome(java.lang.String outcome) {
		this.outcome = outcome;
	}

	public RuleOutcome(java.lang.String outcome) {
		this.outcome = outcome;
	}

}